// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uygwwqhjhozyljuxcgkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Z3d3cWhqaG96eWxqdXhjZ2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzg3MDEsImV4cCI6MjA2NDkxNDcwMX0.6dCc0bIuHKS1xtk7OzkIqrRQKkG43ecTeBsWdLz8aok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});